# This is a basic workflow to help you get started with Actions

name: AutoLogin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "0 1 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - name: make CA
        shell: bash
        run: echo $SSL_CA_B64 | base64 -d > CA.csr
        env:
          SSL_CA_B64: ${{secrets.SSL_CA_B64}}
        
      - name: make PEM
        shell: bash
        run: |
          echo $SSL_PEM_B64 | base64 -d > priv.pem
        env:
          SSL_PEM_B64: ${{secrets.SSL_PEM_B64}}
        
      - name: Setup Python3
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
          
      - name: Install python dependancy
        run : python -m pip install requests

      - name: run musinsa login script
        run: |
          python3 ./musinsa/musinsa.py
        shell: bash
        env:
          MUSINSA_ID: ${{secrets.MUSINSA_ID}}
          MUSINSA_PW: ${{secrets.MUSINSA_PW}}
          
